apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: lesson
data:
  # простые ключ-значение
  APP_ENV: "production"
  APP_PORT: "8080"
  LOG_LEVEL: "info"
  DATABASE_HOST: "postgres.lesson.svc.cluster.local"
