apiVersion: v1
kind: Pod
metadata:
  name: app-secret-volume
  namespace: lesson
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "cat /etc/secrets/DB_PASSWORD && sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: db-secret
  restartPolicy: Never
